### ISSUE TITLE
It stopped to work

### ISSUE THREAD

**Issue by Leksat** [IonBazan/composer-diff-action#8] opened 2022-04-14 09:56 UTC
Got error message today:
```
In PackageDiff.php line 135:

  Could not open file ad66625dce6fd04da4b628f870a7230cce53fd10:apps/silverbac  
  k-drupal/composer.lock or find it in git as ad66625dce6fd04da4b628f870a7230  
  cce53fd10:apps/silverback-drupal/composer.lock 
```

I tried to debug it by adding a new job step:
```
git show ad66625dce6fd04da4b628f870a7230cce53fd10:apps/silverback-drupal/composer.lock
```
This one worked without any issues.

Debugging here: https://github.com/AmazeeLabs/silverback-mono/pull/1021

**Comment by Leksat** [comment] 2022-04-14 10:12
Hmm, when I run the same code as in `\IonBazan\ComposerDiff\PackageDiff::getFileContents`, it works just fine.

Could it be that the action needs some kind of a GitHub permission to read from the git history?

**Comment by adam-delaney** [comment] 2022-04-14 13:58
I am experiencing the same issue. I've checked the workflow permissions on the repo I'm running the action on and it appears to have read permission to the repo.

**Comment by IonBazan** [comment] 2022-04-16 11:08
Thanks for the reporting! I will have a closer look at this after Easter.
My first guess would be that it's related to `actions/checkout` v3 - I am still using v2 in my projects and it worked last time. @Leksat can you help to check if reverting to v2 helps?

**Comment by weitzman** [comment] 2022-04-16 12:18
Affecting me too. I'm pinned to `actions/checkout@v2` and it isn't helping. Debug run at https://github.com/massgov/openmass/runs/6047519645?check_suite_focus=true

**Comment by Leksat** [comment] 2022-04-17 09:26
Confirming. Downgrading `actions/checkout` to`v2` does not help.

**Comment by oradwell** [comment] 2022-04-20 13:57
we're also having this issue :/ on `actions/checkout` v2

**Comment by Leksat** [comment] 2022-04-20 15:52
@IonBazan could you add `git show` output and exit code to the exception [here](https://github.com/IonBazan/composer-diff/blob/7500fe00f5c66319df34c5d0614f073bbf4a095d/src/PackageDiff.php#L135)?

It could give us some hint.

**Comment by IonBazan** [comment] 2022-04-20 16:19
@Leksat @oradwell I found that it's caused by https://github.com/actions/checkout/issues/760 - I will be fixing it now here.

**Comment by IonBazan** [comment] 2022-04-20 16:49
The issue should be now fixed. Please help to verify, @Leksat @oradwell @adam-delaney @weitzman. Here is one of successful runs after the fix: https://github.com/IonBazan/composer-diff-example/pull/1

I have also released [v1.6.1 of Composer-Diff](https://github.com/IonBazan/composer-diff/releases/tag/v1.6.1) which improves git command logging and fixes some minor compatibility problems.

Please note that it only works for repositories referenced in `$GITHUB_WORKSPACE` - any other repo would require adding `git config --global --add safe.directory <path>` to the workflow but at least the error will show some more details on how to fix this problem from now.

**Comment by Leksat** [comment] 2022-04-21 05:50
The error is gone 🎉 Thank you!

Now there is a new little issue. When there are no composer changes, the action output is not empty, but is set to the following:
```::set-output name=composer_diff_exit_code::0```
<img width="872" alt="Screen Shot 2022-04-21 at 08 36 00" src="https://user-images.githubusercontent.com/989015/164382514-88bac9d3-a5e4-4d8d-9e9f-bcf8b68354ba.png">

**Comment by IonBazan** [comment] 2022-04-21 06:08
I believe https://github.com/IonBazan/composer-diff-action/commit/f4eb9f4598cc7d5ac7df67920f8fd333120a696d should fix that - please try to use `IonBazan/composer-diff-action@master` to see if that works.

**Comment by Leksat** [comment] 2022-04-21 06:13
@IonBazan it works like a charm on `master` branch 🎉

**Comment by IonBazan** [comment] 2022-04-21 08:36
@Leksat great! Closing this issue then 🚀

**Closed as completed by IonBazan** 2022-04-21 08:36 UTC

**Comment by oradwell** [comment] 2022-04-21 09:48
thanks both. I can confirm it works flawlessly
